server {
    listen 80;
    server_name localhost;

    # Enable CORS for 3D Tiles consumption by any client
    add_header Access-Control-Allow-Origin *;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
